# Generated by Django 3.2.1 on 2021-05-23 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_type_choice_example', '0003_auto_20210523_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='data_joined',
            new_name='date_joined',
        ),
    ]
